### ISSUE TITLE
Cannot view my assets collection loading indefinitly

### ISSUE THREAD

**Issue by LeeSanFr** [hicetnunc2000/hicetnunc#281]
Hello guys,

Im trying to look at my collection tab, but it is loading indefinitly.
I grab many NFTs from #OBJKT4OBJKT
I think I have to much assets in my collection...
Can you help me ?
Here my wallet adress : tz2L4t9S9LjpR2ca6B869siiKe2Ymp3aQ4gg

Thank you for your help.
LeeSanFr

**Comment by hicetnunc-user-1** [comment]
Possibly important clue:

It was mentioned on discord that this issue seems to be happening to collectors who've never minted before. I tested this, by minting my first OBJKT, and can confirm that my collection reappeared after this! Also, my collection continues to be displayed after burning the single OBJKT in creations.

**Comment by FDF01** [comment]
Ok thanks very much for the info I will mint 1 object! What is your discord link?

**Comment by LeeSanFr** [comment]
Hey :)

Thank you so much for your help.
Im gonna take a look on it and do what you told me 👍 

Have a good day !
Viva HicetNunc !

Best regards
LeeSanFr

**Comment by LeeSanFr** [comment]
Hey !

I 've minted an OBJKT, confirmed in blockchain transaction.
But when I access to 'Manage Assets' nothing is loading ...
Anybody can help ? Much appreciated !

Thanks
LeeSanFr

**Comment by habuw** [comment]
Same here:

Assests Page: https://www.hicetnunc.xyz/tz/tz1WeNABfqppgHhc3Rc29DpzX18TRt34MP4P

**Comment by Cosmognostic** [comment]
Same here.
[my profile](https://www.hicetnunc.xyz/tz/tz1PMxwuDDULaMf4fFvW8N6GXmmaYfrW36Fo)

I can get in to the OBJKTs menu - with 'creations' and 'collection' headings - but trying to view collections just results in the little animated circle going round and round. 
PS I have tried unsyncing and resyncing my wallet. No effect.
This is using a temple wallet, btw When I tied kukai on another account it loaded fine Swapping back to Temple, however - collections still empty

**Comment by FDF01** [comment]
I fixed this by going to OBJKTs (mint NFTs) and mint 1 NFT into my creations!

**Comment by habuw** [comment]
> I fixed this by going to OBJKTs (mint NFTs) and mint 1 NFT into my creations!

However, your asset/profile page is still not available!! :(

**Comment by ArthurOstapenko** [comment]
Same bug here: https://www.hicetnunc.xyz/tz/tz1XZqwn8kasxLXzwe53XhpoWRhRqrQ9HPhV

**Comment by andrevenancio** [comment]
Hey everyone! Thanks for your feedback. should be fixed in next deployment
