### ISSUE TITLE
Aquiring 0 Tez NFT Error

### ISSUE THREAD

**Issue by raynt** [hicetnunc2000/hicetnunc#36]
I've received an error trying to collect 0 (less than 1) Tez NFT using Kukai wallet. The error says:
Error: Forbidden to credit 0ꜩ to a contract without code.
OBJKT#1820

**Comment by dansan566** [comment]
Same with Temple Wallet! I had this issue especially with mtez amount 0.000001

**Comment by crzypatchwork** [comment]
this error should be fixed providing a better UI for inputs

**Comment by raynt** [comment]
I believe the issue is still persisted with Kukai Wallet. Getting the error:
Error: Forbidden to credit 0ꜩ to a contract without code.

An example OBJKT is: https://www.hicetnunc.xyz/objkt/3111#
![Screen Shot 2021-03-09 at 7 17 43 PM](https://user-images.githubusercontent.com/17106015/110556445-84a61680-810c-11eb-8db2-807cb7c39aae.png)

**Comment by skenaja** [comment]
I think the wallets now allow this, as OBJKT 3111 has at least 1 collector. Let us know if it's still a problem.
