### ISSUE TITLE
pdf error during uploading

### ISSUE THREAD

**Issue by TBenesser0** [hicetnunc2000/hicetnunc#863]
i can't see my objkt https://www.hicetnunc.xyz/objkt/126601, but it's in my kukai wallet perfectly showed. probably is a bug on HEN platform.

**To Reproduce**
1. Go to https://www.hicetnunc.xyz/objkt/126601

       or

1. Go to https://www.hicetnunc.xyz/tz/tz1iq2q9dUx7R79ugT2gvTVHriqEt5Cf2Nzx
2. Click on the first objkt 
3. See error

the PDF isn't shown and you cant click on the objkt to open it.

![Cattura](https://user-images.githubusercontent.com/85751130/121704431-10488e00-cad4-11eb-9b06-d9628936ecd5.JPG)

**Desktop**
 - windows 10
 - brave
 - Version 1.25.70.

tz1iq2q9dUx7R79ugT2gvTVHriqEt5Cf2Nzx
OBJKT 126601

**Comment by kylegrover** [comment]
Yes it's a UI bug that showed up recently, #861 should fix this, or switching ipfs gateways I think would also fix. Your PDF is still just fine on chain, nothing wrong with the upload, just need to fix the display.

**Comment by andrevenancio** [comment]
Hi @kylegrover I think #861 has been merged but I still see a warning on this page. `This page has been blocked by Chrome`.

I can access it directly on [IPFS](https://ipfs.io/ipfs/QmWgmZ75NASWGWJ9E6kdgoZk9forh4ZvxVAhQ5ZFdMGz9U) but Chrome and Safari are blocking this content. Works fine on Firefox.

**Comment by violetforest** [comment]
this took a while to load but it seems to be loading. let me know if its still not working for you and i will reopen.
